### ISSUE TITLE
Missing links 

### ISSUE THREAD

**Issue by mafhper** [RakeshPotnuru/Portfolio#5]
The proper path for the links is not being compiled.

There are no "a" tags in the generated html for the blog pages.

**Comment by RakeshPotnuru** [comment]
Hi @mafhper,
Can you give more description of what links are missing?

**Comment by mafhper** [comment]
Sorry for the manners.

When browsing https://itrakesh.co/blogs and hovering over some blog-card, the mouse cursor is changed to pointer, but there are no links or (a tag) in the html code.

`.blog-card {
  background: $color-secondary-2;
  border-radius: $border-radius-1;
  margin: 2%;
  min-height: 18rem;
  cursor: pointer;
  transition: all 0.3s cubic-bezier(0.17, 0.67, 0.64, 0.98);`

So when you click on the blog-card nothing happens.

`<div class="blog-card__content"><p class="blog-card__date"><span>2022-01-31</span></p><div class="blog-card__title my-4"><h6>How I built my portfolio website</h6></div>`

I believe you would like the visitor to be redirected to the blog page in question, which is not happening here.

In the Work tab, there are links under "Details" and "Live Preview" and they are working as expected.

`<div class="text-center col"><a href="/work/projects/Portfolio"><svg>...</svg>&nbsp;Details</a></div>`

**Comment by RakeshPotnuru** [comment]
Links are attached to blogs cards directly. When you click a card it updates the state and set details in blog preview, so the link will be in blog preview only. 
Refer to this video-
https://www.awesomescreenshot.com/video/7166785?key=09836d21bf628c5447246ce8d70acb7f
